BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp

include $(BOARD_DIR)/meta-info.env

DDEFS += -DFIRMWARE_ID=\"KRC_ECU_E36\"
IS_STM32F429 = yes

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE
DDEFS += -DKNOCK_SPECTROGRAM=TRUE

DDEFS += -DEFI_RTC=TRUE
DDEFS += -DRAM_UNUSED_SIZE=1
DDEFS += -DEFI_MAX_31855=TRUE
DDEFS += -DHAL_TRIGGER_USE_PAL=TRUE
DDEFS += -DEFI_MAIN_RELAY_CONTROL=TRUE
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::E8

DDEFS += -DEFI_ENGINE_EMULATOR=FALSE
DDEFS += -DEFI_SENT_SUPPORT=FALSE
DDEFS += -DEFI_MISFIRE_DETECTION=FALSE
DDEFS += -DEFI_ALTERNATOR_CONTROL=FALSE
DDEFS += -DEFI_ENGINE_SNIFFER=FALSE
DDEFS += -DEFI_DYNO_VIEW=FALSE
DDEFS += -DEFI_TCU=FALSE
DDEFS += -DEFI_HPFP=FALSE
DDEFS += -DEFI_WIDEBAND_FIRMWARE_UPDATE=FALSE
DDEFS += -DEFI_EMBED_INI_MSD=FALSE
DDEFS += -DRAMDISK_INVALID

DDEFS += -DEFI_AUX_SERIAL=FALSE
# DDEFS += -DSTM32_SERIAL_USE_USART3=TRUE 
# DDEFS += -DTS_SECONDARY_UxART_PORT=SD3 
# DDEFS += -DEFI_TS_SECONDARY_IS_SERIAL=TRUE

# DDEFS += -DLUA_USER_HEAP=32000
