# List of all the board related files.
BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp

# defines SHORT_BOARD_NAME
include $(BOARD_DIR)/meta-info.env

# Override DEFAULT_ENGINE_TYPE
DDEFS += -DSTM32F407xx
DDEFS += -DFIRMWARE_ID=\"KRC_ECU_F407\"
DDEFS += -DHAL_TRIGGER_USE_PAL=TRUE

# Main Relay control
DDEFS += -DEFI_MAIN_RELAY_CONTROL=TRUE

# Knock
DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE
#DDEFS += -DKNOCK_SPECTROGRAM=TRUE

# EGT
DDEFS += -DEFI_MAX_31855=TRUE

# SENT
DDEFS += -DEFI_SENT_SUPPORT=FALSE

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=1

# Critical LED (Err)
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::E8

# Other 
DDEFS += -DEFI_ENGINE_SNIFFER=FALSE
DDEFS += -DEFI_DYNO_VIEW=FALSE
DDEFS += -DEFI_HPFP=FALSE
DDEFS += -DEFI_WIDEBAND_FIRMWARE_UPDATE=FALSE
DDEFS += -DEFI_EMBED_INI_MSD=FALSE
DDEFS += -DRAMDISK_INVALID

# Lua size
# DDEFS += -DLUA_USER_HEAP=32000

# TS_SECONDARY_UxART_PORT
# DDEFS += -DSTM32_SERIAL_USE_USART3=TRUE 
# DDEFS += -DTS_SECONDARY_UxART_PORT=SD3 
# DDEFS += -DEFI_TS_SECONDARY_IS_SERIAL=TRUE
# DDEFS += -DEFI_AUX_SERIAL=FALSE
